#!/usr/bin/env bash
# Overnight chain (2026-09-26), run from Git Bash on the dev PC:
#   corpus (Mint box) -> merge -> commit -> train both candidates (RTX 4070, WSL) -> LoRA to GGUF
#   -> public guide eval with prompt v2 on the Mint box's 1080 Ti (same hardware/settings as stock).
# The held-out eval is NOT run here: it is used once, for the final pick (training/guide/README.md).
# Log: C:\Users\Ian\cinminai-train-out\overnight.log
set -u
MINT=mint@192.168.5.70
REPO=/c/Users/Ian/Cin-minAI
OUT=/c/Users/Ian/cinminai-train-out
LOG=$OUT/overnight.log
mkdir -p "$OUT"
log() { echo "$(date '+%F %T') $*" | tee -a "$LOG"; }
wslrun() { MSYS_NO_PATHCONV=1 wsl -d Ubuntu-24.04 -e bash -c "$1"; }

log "waiting for the interpretation top-up (interp-topup2) to finish"
until ssh $MINT 'test -f ~/cin-minai/repo-train/interp-topup2/stats.json'; do sleep 120; done

log "stopping the teacher; merging both corpora"
ssh $MINT 'cd ~/cin-minai/repo-train && ./teacherctl.sh stop >/dev/null &&
  python3 training/datasets/merge.py --kind transition --out merged/transition pilot full-rest full-pilot-topics &&
  python3 training/datasets/merge.py --kind interpretation --out merged/interpretation interp interp-topup interp-topup2' \
  >> "$LOG" 2>&1 || { log "MERGE FAILED"; exit 1; }
for k in transition interpretation; do
  scp -q $MINT:cin-minai/repo-train/merged/$k/corpus.jsonl $MINT:cin-minai/repo-train/merged/$k/merge-stats.json \
    "$REPO/training/datasets/$k/" || { log "COPY FAILED ($k)"; exit 1; }
done
cd "$REPO" && git add training/datasets/transition/corpus.jsonl training/datasets/transition/merge-stats.json \
  training/datasets/interpretation/corpus.jsonl training/datasets/interpretation/merge-stats.json &&
  git commit -q -m "Guide corpus, cycle 0: transition + interpretation (merged, cleaned, decontaminated)

Generated by Qwen3-14B (local teacher) with training/datasets/*/generate.py; merged with
training/datasets/merge.py. Datasheet follows.

Co-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>" && git push -q && log "corpus committed: $(git log --oneline -1)"

log "preparing the training file in WSL"
wslrun 'mkdir -p ~/cinminai-train/data && cat /mnt/c/Users/Ian/Cin-minAI/training/datasets/transition/corpus.jsonl \
  /mnt/c/Users/Ian/Cin-minAI/training/datasets/interpretation/corpus.jsonl > ~/cinminai-train/data/guide-c0.jsonl &&
  wc -l ~/cinminai-train/data/guide-c0.jsonl' >> "$LOG" 2>&1

train_and_eval() {  # name, base dir, targets, base GGUF on the Mint box
  local name=$1 base=$2 targets=$3 gguf=$4
  log "training $name (targets: $targets)"
  wslrun "cd ~/cinminai-train && .venv/bin/python /mnt/c/Users/Ian/Cin-minAI/training/guide/train_lora.py \
    --base base/$base --data data/guide-c0.jsonl --out runs/c0-$name --epochs 2 --targets $targets" >> "$LOG" 2>&1 \
    || { log "TRAINING FAILED: $name"; return 1; }
  wslrun "cd ~/cinminai-train && .venv/bin/python llama.cpp/convert_lora_to_gguf.py runs/c0-$name/adapter \
    --base base/$base --outfile out/c0-$name-lora.gguf --outtype f16 && cp out/c0-$name-lora.gguf runs/c0-$name/run.json \
    /mnt/c/Users/Ian/cinminai-train-out/ 2>/dev/null; cp runs/c0-$name/run.json /mnt/c/Users/Ian/cinminai-train-out/run-$name.json" \
    >> "$LOG" 2>&1 || { log "CONVERSION FAILED: $name"; return 1; }
  scp -q "$OUT/c0-$name-lora.gguf" $MINT:cin-minai/adapters/ || { log "UPLOAD FAILED: $name"; return 1; }
  log "public eval (prompt v2) for $name + adapter on the 1080 Ti"
  ssh $MINT "cd ~/cin-minai/eval-guide &&
    while [ \$(nvidia-smi --query-compute-apps=used_memory --format=csv,noheader,nounits | awk '{s+=\$1} END {print s+0}') -gt 512 ]; do sleep 60; done
    ~/cin-minai/llama.cpp/build-cuda/bin/llama-server --host 127.0.0.1 --port 18090 --model ~/cin-minai/models/$gguf \
      --lora ~/cin-minai/adapters/c0-$name-lora.gguf --ctx-size 8192 --gpu-layers all --cache-type-k q8_0 --cache-type-v q8_0 \
      --flash-attn on --fit off --parallel 1 --reasoning off --alias c0-$name > bench-results/guide/server-c0-$name.log 2>&1 &
    pid=\$!; for i in \$(seq 120); do curl -sf http://127.0.0.1:18090/health >/dev/null && break; sleep 1; done
    python3 run_eval.py --prompt v2 --url http://127.0.0.1:18090 --model c0-$name --out bench-results/guide/c0-$name-v2.jsonl \
      > bench-results/guide/c0-$name-v2.txt 2>&1; kill \$pid; wait \$pid 2>/dev/null
    sed -n '/^ALL/,/^ja/p' bench-results/guide/c0-$name-v2.txt" >> "$LOG" 2>&1
  scp -q $MINT:cin-minai/eval-guide/bench-results/guide/c0-$name-v2.txt "$OUT/" 2>/dev/null
  log "done: $name"
}

eval_stock() {  # name, base GGUF: stock model, prompt v2, current scorer — the fair "before"
  local name=$1 gguf=$2
  log "public eval (prompt v2, current scorer) for stock $name"
  ssh $MINT "cd ~/cin-minai/eval-guide &&
    while [ \$(nvidia-smi --query-compute-apps=used_memory --format=csv,noheader,nounits | awk '{s+=\$1} END {print s+0}') -gt 512 ]; do sleep 60; done
    ~/cin-minai/llama.cpp/build-cuda/bin/llama-server --host 127.0.0.1 --port 18090 --model ~/cin-minai/models/$gguf       --ctx-size 8192 --gpu-layers all --cache-type-k q8_0 --cache-type-v q8_0 --flash-attn on --fit off --parallel 1       --reasoning off --alias stock-$name > bench-results/guide/server-stock-$name.log 2>&1 &
    pid=\$!; for i in \$(seq 120); do curl -sf http://127.0.0.1:18090/health >/dev/null && break; sleep 1; done
    python3 run_eval.py --prompt v2 --url http://127.0.0.1:18090 --model stock-$name --out bench-results/guide/stock-$name-v2b.jsonl       > bench-results/guide/stock-$name-v2b.txt 2>&1; kill \$pid; wait \$pid 2>/dev/null
    sed -n '/^ALL/,/^ja/p' bench-results/guide/stock-$name-v2b.txt" >> "$LOG" 2>&1
  scp -q $MINT:cin-minai/eval-guide/bench-results/guide/stock-$name-v2b.txt "$OUT/" 2>/dev/null
}

# the eval scripts on the Mint box must match the repo (scorer fixes, prompt v2)
scp -q "$REPO/training/eval/guide/run_eval.py" "$REPO/training/eval/guide/tasks.py" "$REPO/training/eval/guide/labels.json" \
  $MINT:cin-minai/eval-guide/

eval_stock Qwen3.5-4B Qwen3.5-4B-Q4_K_M.gguf
eval_stock gemma-4-E2B gemma-4-E2B_q4_0-it.gguf

# Qwen first (fits in 12 GB, finishes sooner); Qwen3.5's linear-attention projections are left out (see train_lora.py)
train_and_eval Qwen3.5-4B Qwen3.5-4B q_proj,k_proj,v_proj,o_proj,gate_proj,up_proj,down_proj Qwen3.5-4B-Q4_K_M.gguf
train_and_eval gemma-4-E2B gemma-4-E2B-it all-linear gemma-4-E2B_q4_0-it.gguf
log "OVERNIGHT CHAIN FINISHED"
