# SPDX-License-Identifier: GPL-3.0-or-later
"""Cin-MinAI wallpapers: vector art after Ian's concept images (concepts/, the mood board).

Deterministic (fixed seeds): the same script gives the same pictures. Palette from ../colors.md. Glow is
drawn as stacked soft strokes, not blur filters, so every SVG renderer shows the same thing. The top-left
quarter (desktop icons) is kept calm. Writes <name>.svg; with --png also <name>.png at 3840x2160.

    uv run --with cairosvg python generate.py [--png] [--preview 1600]

  circuit-floor  a circuit plane running into the distance, a glow at the vanishing point, binary above
  data-stream    streams of light flowing into the distance over a dark board
  board          a close-up board: a glowing chip, traces running off it, binary in the air
"""
from __future__ import annotations

import argparse
import math
import os
import random

W, H = 3840, 2160
BLUE, GREEN, CYAN, TEAL, PANEL = "#00A4EC", "#18D42C", "#34B5B8", "#106979", "#02141C"
HERE = os.path.dirname(os.path.abspath(__file__))


class Svg:
    def __init__(self):
        self.defs, self.body = [], []

    def add(self, s):
        self.body.append(s)

    def text(self):
        return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" width="{W}" height="{H}">'
                f'<!-- Cin-MinAI wallpaper, generated by generate.py. CC BY-SA 4.0 -->'
                f'<defs>{"".join(self.defs)}</defs>{"".join(self.body)}</svg>\n')


def pts(p):
    return " ".join(f"{x:.1f},{y:.1f}" for x, y in p)


def glow_line(svg, p, color, width, strength=1.0, core=True):
    """A glowing polyline: wide faint strokes under a bright thin core."""
    for mult, op in ((9, 0.035), (5, 0.06), (2.6, 0.14)):
        svg.add(f'<polyline points="{pts(p)}" fill="none" stroke="{color}" stroke-width="{width * mult:.1f}" '
                f'stroke-linecap="round" stroke-linejoin="round" opacity="{op * strength:.3f}"/>')
    if core:
        svg.add(f'<polyline points="{pts(p)}" fill="none" stroke="{color}" stroke-width="{width:.1f}" '
                f'stroke-linecap="round" stroke-linejoin="round" opacity="{min(1, 0.85 * strength):.3f}"/>')


def glow_dot(svg, x, y, r, color, strength=1.0):
    for mult, op in ((6, 0.05), (3, 0.12)):
        svg.add(f'<circle cx="{x:.1f}" cy="{y:.1f}" r="{r * mult:.1f}" fill="{color}" opacity="{op * strength:.3f}"/>')
    svg.add(f'<circle cx="{x:.1f}" cy="{y:.1f}" r="{r:.1f}" fill="{color}" opacity="{min(1, 0.9 * strength):.3f}"/>')


def background(svg, cx, cy, inner=PANEL):
    svg.defs.append(f'<radialGradient id="bg" cx="{cx / W:.3f}" cy="{cy / H:.3f}" r="0.75">'
                    f'<stop offset="0" stop-color="{inner}"/><stop offset="0.55" stop-color="#010A0F"/>'
                    f'<stop offset="1" stop-color="#000000"/></radialGradient>')
    svg.add(f'<rect width="{W}" height="{H}" fill="url(#bg)"/>')


def calm_corner(svg):
    """Darken the top-left (desktop icons) so they stay readable."""
    svg.defs.append('<radialGradient id="calm" cx="0" cy="0" r="0.55">'
                    '<stop offset="0" stop-color="#000000" stop-opacity="0.7"/>'
                    '<stop offset="1" stop-color="#000000" stop-opacity="0"/></radialGradient>')
    svg.add(f'<rect width="{W}" height="{H}" fill="url(#calm)"/>')


def binary_digit(svg, x, y, size, one, color, op):
    """Our own 0 and 1 (no font needed): a slim bar, or a rounded outline."""
    w = size * 0.5
    if one:
        svg.add(f'<rect x="{x + w * 0.4:.1f}" y="{y:.1f}" width="{size * 0.13:.1f}" height="{size:.1f}" '
                f'rx="{size * 0.05:.1f}" fill="{color}" opacity="{op:.3f}"/>')
    else:
        svg.add(f'<rect x="{x:.1f}" y="{y:.1f}" width="{w:.1f}" height="{size:.1f}" rx="{w * 0.45:.1f}" fill="none" '
                f'stroke="{color}" stroke-width="{size * 0.11:.1f}" opacity="{op:.3f}"/>')


def binary_columns(svg, rnd, x0, x1, y_bottom, count, size_range, avoid=None):
    for _ in range(count):
        x = rnd.uniform(x0, x1)
        size = rnd.uniform(*size_range)
        if avoid and avoid(x, 0):
            continue
        color = rnd.choice([GREEN, CYAN, BLUE, GREEN])
        y = rnd.uniform(-size * 4, y_bottom * 0.3)
        n = rnd.randint(6, 22)
        for k in range(n):
            yy = y + k * size * 1.35
            if yy > y_bottom:
                break
            fade = (1 - k / n) * rnd.uniform(0.35, 0.9) * (1 - yy / (y_bottom * 1.3))
            if avoid and avoid(x, yy):
                fade *= 0.15
            if fade > 0.03:
                binary_digit(svg, x, yy, size, rnd.random() < 0.5, color, fade)


def trace(rnd, x, y, steps, step_len, dirs=(0, 1, 2, 3, 4, 5, 6, 7), start_dir=None):
    """A circuit trace: straight runs with 45-degree bends."""
    d = start_dir if start_dir is not None else rnd.choice(dirs)
    p = [(x, y)]
    for _ in range(steps):
        run = rnd.randint(2, 6) * step_len
        dx, dy = math.cos(d * math.pi / 4), math.sin(d * math.pi / 4)
        x, y = x + dx * run, y + dy * run
        p.append((x, y))
        d = (d + rnd.choice([-1, 0, 0, 1])) % 8
        if d not in dirs:
            d = rnd.choice(dirs)
    return p


# --- 1. circuit floor --------------------------------------------------------------------------------

def circuit_floor(seed=11):
    rnd, svg = random.Random(seed), Svg()
    vx, vy = W * 0.5, H * 0.46            # vanishing point
    background(svg, vx, vy)

    def project(u, v):                    # plane coords: u across, v >= 1 into the distance
        return vx + u / v, vy + 1150 / v

    # glow at the vanishing point
    svg.defs.append(f'<radialGradient id="core" cx="0.5" cy="0.5" r="0.5"><stop offset="0" stop-color="{CYAN}" '
                    f'stop-opacity="0.55"/><stop offset="0.35" stop-color="{BLUE}" stop-opacity="0.18"/>'
                    f'<stop offset="1" stop-color="{BLUE}" stop-opacity="0"/></radialGradient>')
    svg.add(f'<ellipse cx="{vx}" cy="{vy}" rx="1400" ry="700" fill="url(#core)"/>')
    # towers: tall glass panels on both sides, fading with distance
    for side in (-1, 1):
        for k in range(14):
            v = 1.2 + k * 0.55
            u = side * rnd.uniform(1500, 2600)
            x, yb = project(u, v)
            hgt = rnd.uniform(900, 1700) / v
            wd = rnd.uniform(160, 380) / v
            op = 0.5 / (1 + k * 0.35)
            svg.add(f'<rect x="{x - wd / 2:.1f}" y="{yb - hgt:.1f}" width="{wd:.1f}" height="{hgt:.1f}" '
                    f'fill="{PANEL}" stroke="{rnd.choice([BLUE, TEAL, GREEN])}" stroke-width="{3 / v + 0.6:.1f}" '
                    f'opacity="{op + 0.2:.2f}"/>')
            for j in range(int(hgt // (40 / v + 8))):
                if rnd.random() < 0.45:
                    yy = yb - hgt + (j + 0.5) * (40 / v + 8)
                    svg.add(f'<rect x="{x - wd / 2 + wd * 0.15:.1f}" y="{yy:.1f}" width="{wd * rnd.uniform(0.2, 0.7):.1f}" '
                            f'height="{max(1.5, 5 / v):.1f}" fill="{rnd.choice([CYAN, GREEN, BLUE])}" opacity="{op:.2f}"/>')
    # binary columns in the air (avoid the calm corner)
    binary_columns(svg, rnd, 0, W, vy - 80, 70, (18, 46), avoid=lambda x, y: x < W * 0.28 and y < H * 0.4)
    # the floor: grid lines and traces in perspective
    for u in range(-6000, 6001, 400):
        a, b = project(u, 1.0), project(u, 12)
        svg.add(f'<line x1="{a[0]:.1f}" y1="{a[1]:.1f}" x2="{b[0]:.1f}" y2="{b[1]:.1f}" stroke="{TEAL}" '
                f'stroke-width="1.6" opacity="0.28"/>')
    for i in range(24):
        v = 1.0 + (i ** 1.6) * 0.07
        a, b = project(-7000, v), project(7000, v)
        svg.add(f'<line x1="{a[0]:.1f}" y1="{a[1]:.1f}" x2="{b[0]:.1f}" y2="{b[1]:.1f}" stroke="{TEAL}" '
                f'stroke-width="1.4" opacity="{0.3 / (1 + i * 0.08):.3f}"/>')
    for _ in range(90):
        u0, v0 = rnd.uniform(-5200, 5200), rnd.uniform(1.0, 6)
        grid = trace(rnd, 0, 0, rnd.randint(3, 7), 1, dirs=(0, 2, 4, 6, 1, 3))   # on a flat grid...
        path = [(u0 + a * 120, max(1.0, v0 + b * 0.06)) for a, b in grid]     # ...laid onto the floor
        scr = [project(pu, pv) for pu, pv in path]
        color = rnd.choice([BLUE, BLUE, CYAN, GREEN])
        width = 4.2 / path[0][1]
        glow_line(svg, scr, color, width, strength=1.1 / path[0][1] ** 0.5)
        glow_dot(svg, *scr[-1], r=width * 1.6, color=color, strength=1 / path[0][1] ** 0.5)
    # the central "gate": nested frames at the vanishing point
    for k in range(6):
        s = 520 - k * 70
        svg.add(f'<rect x="{vx - s:.1f}" y="{vy - s * 0.62:.1f}" width="{2 * s:.1f}" height="{s * 1.24:.1f}" rx="{s * 0.08:.1f}" '
                f'fill="none" stroke="{[BLUE, CYAN, GREEN][k % 3]}" stroke-width="{3 + k * 0.5:.1f}" opacity="{0.18 + k * 0.08:.2f}"/>')
    glow_dot(svg, vx, vy, 7, "#E6F4F8", strength=1.0)
    calm_corner(svg)
    return svg


# --- 2. data stream ----------------------------------------------------------------------------------

def data_stream(seed=23):
    rnd, svg = random.Random(seed), Svg()
    vx, vy = W * 0.62, H * 0.5
    background(svg, vx, vy)
    svg.defs.append(f'<radialGradient id="core" cx="0.5" cy="0.5" r="0.5"><stop offset="0" stop-color="{CYAN}" '
                    f'stop-opacity="0.6"/><stop offset="1" stop-color="{BLUE}" stop-opacity="0"/></radialGradient>')
    svg.add(f'<ellipse cx="{vx}" cy="{vy}" rx="1100" ry="420" fill="url(#core)"/>')
    # distant city: thin bright columns along the horizon
    for _ in range(160):
        x = rnd.uniform(W * 0.25, W)
        hgt = rnd.uniform(60, 700) * (1 - abs(x - vx) / W)
        svg.add(f'<rect x="{x:.1f}" y="{vy - hgt:.1f}" width="{rnd.uniform(4, 22):.1f}" height="{hgt:.1f}" '
                f'fill="{rnd.choice([BLUE, CYAN, TEAL])}" opacity="{rnd.uniform(0.08, 0.35):.2f}"/>')
    binary_columns(svg, rnd, W * 0.3, W, vy, 60, (16, 40), avoid=lambda x, y: x < W * 0.32 and y < H * 0.45)
    # streams: bundles of curves from the lower left, bending into the vanishing point
    for bundle in range(5):
        x0 = rnd.uniform(-600, W * 0.7)
        y0 = H + rnd.uniform(0, 300)
        c1 = (rnd.uniform(W * 0.1, W * 0.6), rnd.uniform(H * 0.55, H * 0.95))
        color = [BLUE, GREEN, CYAN, BLUE, GREEN][bundle]
        for k in range(rnd.randint(6, 12)):
            off = (k - 5) * rnd.uniform(14, 28)
            path = []
            for t in [i / 60 for i in range(61)]:
                # quadratic curve from (x0, y0) via c1 to the vanishing point, spread by off, narrowing
                x = (1 - t) ** 2 * (x0 + off * 3) + 2 * (1 - t) * t * (c1[0] + off * 2) + t * t * vx
                y = (1 - t) ** 2 * y0 + 2 * (1 - t) * t * (c1[1] + off) + t * t * (vy + 8)
                path.append((x, y))
            width = rnd.uniform(1.6, 4.5)
            glow_line(svg, path, color, width, strength=rnd.uniform(0.5, 1.1))
            # light pulses along the stream
            for t in sorted(rnd.random() for _ in range(rnd.randint(2, 6))):
                x, y = path[int(t * 60)]
                glow_dot(svg, x, y, width * 1.8 * (1.3 - t), "#E6F4F8" if rnd.random() < 0.3 else color, 0.9)
    # the board underneath: faint traces in the lower third
    for _ in range(70):
        p = trace(rnd, rnd.uniform(0, W), rnd.uniform(H * 0.62, H), rnd.randint(3, 6), 40)
        glow_line(svg, p, rnd.choice([TEAL, BLUE, GREEN]), 2.0, strength=0.35)
    calm_corner(svg)
    return svg


# --- 3. board ----------------------------------------------------------------------------------------

def board(seed=37):
    rnd, svg = random.Random(seed), Svg()
    chip_x, chip_y = W * 0.7, H * 0.55
    background(svg, chip_x, chip_y)
    # far layer: small faint components (soft, out of focus)
    for _ in range(120):
        x, y = rnd.uniform(0, W), rnd.uniform(H * 0.25, H)
        w, h = rnd.uniform(30, 140), rnd.uniform(20, 90)
        svg.add(f'<rect x="{x:.1f}" y="{y:.1f}" width="{w:.1f}" height="{h:.1f}" rx="6" fill="#031E27" '
                f'stroke="{TEAL}" stroke-width="2" opacity="{rnd.uniform(0.25, 0.6):.2f}"/>')
    binary_columns(svg, rnd, 0, W, H * 0.55, 55, (14, 36), avoid=lambda x, y: x < W * 0.3 and y < H * 0.42)
    # traces running off the chip, in bundles, with 45-degree bends
    for side, dirs in ((0, (4, 3, 5)), (1, (0, 1, 7)), (2, (6, 5, 7)), (3, (2, 1, 3))):
        for k in range(16):
            sx = chip_x + [-380, 380, 0, 0][side] + ([0, 0, -300, -300][side] + [0, 0, 40, 40][side] * k)
            sy = chip_y + [0, 0, -260, 260][side] + ([-240, -240, 0, 0][side] + [30, 30, 0, 0][side] * k)
            p = trace(rnd, sx, sy, rnd.randint(4, 8), 38, dirs=dirs, start_dir=dirs[0])
            color = rnd.choice([BLUE, BLUE, CYAN, GREEN])
            glow_line(svg, p, color, rnd.uniform(2.2, 4.2), strength=rnd.uniform(0.6, 1.1))
            glow_dot(svg, *p[-1], r=5, color=color)
    # scattered traces elsewhere (fewer in the calm corner)
    for _ in range(80):
        x, y = rnd.uniform(0, W), rnd.uniform(H * 0.2, H)
        if x < W * 0.3 and y < H * 0.45:
            continue
        p = trace(rnd, x, y, rnd.randint(3, 6), 34)
        glow_line(svg, p, rnd.choice([TEAL, BLUE, GREEN]), 2.0, strength=0.45)
    # the chip: body, pins, glowing edge
    cw, ch = 760, 520
    for i in range(22):
        for (x1, y1, x2, y2) in ((chip_x - cw / 2 + 30 + i * 32, chip_y - ch / 2, 0, -40),
                                 (chip_x - cw / 2 + 30 + i * 32, chip_y + ch / 2, 0, 40)):
            svg.add(f'<rect x="{x1:.1f}" y="{min(y1, y1 + y2):.1f}" width="12" height="40" fill="#8FB8C4" opacity="0.55"/>')
    for i in range(15):
        for x1 in (chip_x - cw / 2 - 40, chip_x + cw / 2):
            svg.add(f'<rect x="{x1:.1f}" y="{chip_y - ch / 2 + 30 + i * 32:.1f}" width="40" height="12" fill="#8FB8C4" opacity="0.55"/>')
    glow_line(svg, [(chip_x - cw / 2, chip_y - ch / 2), (chip_x + cw / 2, chip_y - ch / 2), (chip_x + cw / 2, chip_y + ch / 2),
                    (chip_x - cw / 2, chip_y + ch / 2), (chip_x - cw / 2, chip_y - ch / 2)], BLUE, 5, strength=1.3)
    svg.add(f'<rect x="{chip_x - cw / 2:.1f}" y="{chip_y - ch / 2:.1f}" width="{cw}" height="{ch}" rx="14" fill="#04202B"/>')
    svg.add(f'<rect x="{chip_x - cw / 2 + 60:.1f}" y="{chip_y - ch / 2 + 50:.1f}" width="{cw - 120}" height="{ch - 100}" rx="10" '
            f'fill="#062C3A" stroke="{CYAN}" stroke-width="2" opacity="0.9"/>')
    calm_corner(svg)
    return svg


WALLPAPERS = {"circuit-floor": circuit_floor, "data-stream": data_stream, "board": board}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--png", action="store_true", help="also render <name>.png at 3840x2160")
    ap.add_argument("--preview", type=int, help="also render <name>-preview.png at this width (for review)")
    o = ap.parse_args()
    for name, make in WALLPAPERS.items():
        text = make().text()
        path = os.path.join(HERE, f"{name}.svg")
        open(path, "w", encoding="utf-8", newline="\n").write(text)
        print(f"{name}.svg  {len(text) / 1e6:.1f} MB")
        if o.png or o.preview:
            import cairosvg
            if o.png:
                cairosvg.svg2png(bytestring=text.encode(), write_to=os.path.join(HERE, f"{name}.png"),
                                 output_width=W, output_height=H)
            if o.preview:
                cairosvg.svg2png(bytestring=text.encode(), write_to=os.path.join(HERE, f"{name}-preview.png"),
                                 output_width=o.preview, output_height=o.preview * H // W)


if __name__ == "__main__":
    main()
