#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Create the checked-in ISO package/version inventory from filesystem.manifest.

The input may be a manifest, a local ISO, or an HTTP(S) ISO.  Remote ISOs are
read with byte-range requests; the multi-gigabyte image is not downloaded.
"""

from __future__ import annotations

import argparse
import os
import struct
import sys
import urllib.request

SECTOR = 2048


class Reader:
    def __init__(self, source: str):
        self.source = source

    def read(self, start: int, size: int) -> bytes:
        if self.source.startswith(("http://", "https://")):
            request = urllib.request.Request(self.source, headers={"Range": f"bytes={start}-{start + size - 1}", "User-Agent": "Cin-MinAI-SBOM/0.0.1"})
            with urllib.request.urlopen(request, timeout=60) as response:
                # Limit the read even if a server ignores Range; never turn an
                # inventory refresh into an accidental multi-gigabyte download.
                data = response.read(size + 1)
        else:
            with open(self.source, "rb") as stream:
                stream.seek(start)
                data = stream.read(size)
        if len(data) != size:
            raise ValueError(f"short read at {start}: wanted {size}, got {len(data)}")
        return data


def directory_record(raw: bytes) -> tuple[int, int, bool, str]:
    extent = struct.unpack_from("<I", raw, 2)[0]
    size = struct.unpack_from("<I", raw, 10)[0]
    is_dir = bool(raw[25] & 2)
    length = raw[32]
    name = raw[33:33 + length].decode("utf-8", "replace").split(";", 1)[0]
    return extent, size, is_dir, name


def entries(reader: Reader, extent: int, size: int):
    data = reader.read(extent * SECTOR, size)
    offset = 0
    while offset < len(data):
        length = data[offset]
        if not length:
            offset = (offset // SECTOR + 1) * SECTOR
            continue
        yield directory_record(data[offset:offset + length])
        offset += length


def iso_file(source: str, components: list[str]) -> bytes:
    reader = Reader(source)
    pvd = reader.read(16 * SECTOR, SECTOR)
    if pvd[:7] != b"\x01CD001\x01":
        raise ValueError("not an ISO-9660 primary volume descriptor")
    extent, size, is_dir, _ = directory_record(pvd[156:])
    for index, wanted in enumerate(components):
        found = None
        for item in entries(reader, extent, size):
            if item[3].lower() == wanted.lower():
                found = item
                break
        if found is None:
            raise FileNotFoundError("/" + "/".join(components[:index + 1]))
        extent, size, is_dir, _ = found
        if index < len(components) - 1 and not is_dir:
            raise NotADirectoryError(wanted)
    if is_dir:
        raise IsADirectoryError(components[-1])
    return reader.read(extent * SECTOR, size)


def manifest(source: str) -> bytes:
    if source.endswith(".manifest") or source.endswith(".txt"):
        if source.startswith(("http://", "https://")):
            with urllib.request.urlopen(source, timeout=60) as response:
                return response.read()
        with open(source, "rb") as stream:
            return stream.read()
    return iso_file(source, ["casper", "filesystem.manifest"])


def inventory(data: bytes, source: str) -> str:
    packages = []
    for number, line in enumerate(data.decode("utf-8").splitlines(), 1):
        parts = line.split("\t")
        if len(parts) != 2 or not all(parts):
            raise ValueError(f"bad manifest line {number}: {line!r}")
        packages.append(tuple(parts))
    packages.sort(key=lambda item: (item[0].lower(), item[0]))
    if len(packages) != len({name for name, _ in packages}):
        raise ValueError("manifest contains duplicate package names")
    header = [
        "# Cin-MinAI 0.0.1 ISO package inventory",
        "# Generated by distro/iso-package-inventory.py from /casper/filesystem.manifest.",
        f"# Source: {source}",
        f"# Packages: {len(packages)}",
        "package\tversion",
    ]
    return "\n".join(header + [f"{name}\t{version}" for name, version in packages]) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", help="filesystem.manifest path, ISO path, or ISO URL")
    parser.add_argument("output", nargs="?", help="output TSV (stdout when omitted)")
    args = parser.parse_args()
    text = inventory(manifest(args.source), args.source)
    if args.output:
        with open(args.output, "w", encoding="utf-8", newline="\n") as stream:
            stream.write(text)
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
